name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: 
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        platforms: linux/amd64,linux/arm64
        # List of tags
        tags: |
          ghcr.io/${{ github.repository_owner }}/bili-fav-sniffer:latest
